### ISSUE TITLE
Add option to log ALL flights

### ISSUE THREAD

**Issue by tobiz** [tobiz/OGN-Flight-Logger_V2#4]
An option is needed to log all flights from an airfield not just flights of aircraft registered at the airfield.  This extends the original intent of the project but could be useful for several reasons.

**Comment by tobiz** [comment]
Done.  Code added but not fully tested as my 'local' OGN Rx seems to be down. However the initial consequence is that it is only possible to log glider only flights if "log all flights" is not selected; I'll look into this.  Reason: the full OGN glider db is now used and this doesn't have a field for 'type of aircraft'.  In addition since the full OGN db is now used (>4k records) I've added an index for searching the database by flarm id to resolve flarm id to aircraft registration.

**Comment by kerel-fs** [comment]
Hi @tobiz,

> the full OGN glider db is now used and this doesn't have a field for 'type of aircraft'

The ogn-ddb does have a field `aircraft_type`, but it's hidden by default (for whatever reason),
see [ogn-ddb#url-parameters](https://github.com/glidernet/ogn-ddb#url-parameters). e.g. `https://ddb.glidernet.org/download?j=1&t=1`.

Incidentally I recommend you to have a look at [python-ogn-client](https://github.com/glidernet/python-ogn-client), which provides an OGN/APRS-client and an ogn-ddb-client:

``` python
from ogn.ddb import get_ddb_devices
devices = list(get_ddb_devices())
```

**Comment by tobiz** [comment]
Interesting, I'll take a look.
